// ─── 24h Telemetry (hourly) ──────────────────────────────────────────────────
export const mockTelemetryData = [
  { time: '00:00', cpu: 35, memory: 45, responseTime: 120, errorRate: 0.1 },
  { time: '01:00', cpu: 42, memory: 48, responseTime: 145, errorRate: 0.2 },
  { time: '02:00', cpu: 38, memory: 42, responseTime: 110, errorRate: 0.1 },
  { time: '03:00', cpu: 45, memory: 52, responseTime: 165, errorRate: 0.3 },
  { time: '04:00', cpu: 52, memory: 58, responseTime: 185, errorRate: 0.2 },
  { time: '05:00', cpu: 48, memory: 55, responseTime: 155, errorRate: 0.2 },
  { time: '06:00', cpu: 65, memory: 72, responseTime: 240, errorRate: 0.5 },
  { time: '07:00', cpu: 78, memory: 85, responseTime: 320, errorRate: 0.8 },
  { time: '08:00', cpu: 72, memory: 80, responseTime: 280, errorRate: 0.6 },
  { time: '09:00', cpu: 85, memory: 88, responseTime: 385, errorRate: 1.2 },
  { time: '10:00', cpu: 68, memory: 75, responseTime: 250, errorRate: 0.4 },
  { time: '11:00', cpu: 62, memory: 70, responseTime: 215, errorRate: 0.3 },
  { time: '12:00', cpu: 58, memory: 68, responseTime: 198, errorRate: 0.3 },
  { time: '13:00', cpu: 71, memory: 74, responseTime: 262, errorRate: 0.5 },
  { time: '14:00', cpu: 80, memory: 82, responseTime: 340, errorRate: 0.9 },
  { time: '15:00', cpu: 76, memory: 79, responseTime: 305, errorRate: 0.7 },
  { time: '16:00', cpu: 69, memory: 73, responseTime: 255, errorRate: 0.4 },
  { time: '17:00', cpu: 55, memory: 63, responseTime: 188, errorRate: 0.2 },
  { time: '18:00', cpu: 48, memory: 58, responseTime: 162, errorRate: 0.2 },
  { time: '19:00', cpu: 43, memory: 54, responseTime: 140, errorRate: 0.1 },
  { time: '20:00', cpu: 39, memory: 50, responseTime: 125, errorRate: 0.1 },
  { time: '21:00', cpu: 36, memory: 47, responseTime: 118, errorRate: 0.1 },
  { time: '22:00', cpu: 33, memory: 44, responseTime: 112, errorRate: 0.1 },
  { time: '23:00', cpu: 30, memory: 41, responseTime: 105, errorRate: 0.1 },
];

// ─── Incidents (15 entries) ──────────────────────────────────────────────────
export const mockIncidents = [
  {
    id: 'INC-001',
    severity: 'critical' as const,
    title: 'High CPU Utilization Detected',
    description: 'CPU usage exceeded 85% threshold on primary API gateway service. AutoScaler-Alpha initiated scale-up sequence.',
    status: 'investigating' as const,
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
    resolved_at: null,
    affected_service: 'API Gateway',
    assigned_agent: 'AutoScaler-Alpha',
    impact: 'High',
    timeline: [
      { time: new Date(Date.now() - 5 * 60000).toISOString(), event: 'Incident detected by HealthMonitor-Gamma' },
      { time: new Date(Date.now() - 4 * 60000).toISOString(), event: 'AutoScaler-Alpha assigned for remediation' },
      { time: new Date(Date.now() - 2 * 60000).toISOString(), event: 'Scale-up command issued to 4 new instances' },
    ],
  },
  {
    id: 'INC-002',
    severity: 'high' as const,
    title: 'Memory Pressure Warning',
    description: 'Memory usage trending towards critical level at 88%. Possible memory leak in cache layer identified.',
    status: 'active' as const,
    created_at: new Date(Date.now() - 12 * 60000).toISOString(),
    resolved_at: null,
    affected_service: 'Database Service',
    assigned_agent: 'MemoryOptimizer-Beta',
    impact: 'Medium',
    timeline: [
      { time: new Date(Date.now() - 12 * 60000).toISOString(), event: 'Alert triggered: memory >80%' },
      { time: new Date(Date.now() - 10 * 60000).toISOString(), event: 'MemoryOptimizer-Beta engaged' },
    ],
  },
  {
    id: 'INC-003',
    severity: 'medium' as const,
    title: 'Increased Response Time',
    description: 'Average response time increased by 35% over baseline. Potential bottleneck in web service layer.',
    status: 'active' as const,
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    resolved_at: null,
    affected_service: 'Web Service',
    assigned_agent: 'ResponseUnit-Epsilon',
    impact: 'Low',
    timeline: [
      { time: new Date(Date.now() - 25 * 60000).toISOString(), event: 'Response time SLA breach detected' },
      { time: new Date(Date.now() - 20 * 60000).toISOString(), event: 'ResponseUnit-Epsilon investigating' },
    ],
  },
  {
    id: 'INC-004',
    severity: 'critical' as const,
    title: 'DDoS Attack Pattern Detected',
    description: 'Anomalous traffic spike of 4.2x normal volume from multiple source IPs. Mitigation in progress.',
    status: 'investigating' as const,
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
    resolved_at: null,
    affected_service: 'Load Balancer',
    assigned_agent: 'NetworkDefense-Delta',
    impact: 'Critical',
    timeline: [
      { time: new Date(Date.now() - 8 * 60000).toISOString(), event: 'Traffic anomaly detected' },
      { time: new Date(Date.now() - 7 * 60000).toISOString(), event: 'NetworkDefense-Delta deployed firewall rules' },
      { time: new Date(Date.now() - 5 * 60000).toISOString(), event: 'Rate limiting applied to 847 IPs' },
    ],
  },
  {
    id: 'INC-005',
    severity: 'high' as const,
    title: 'Database Connection Pool Exhausted',
    description: 'Connection pool reached 100% utilization. New requests queuing with 2s+ wait times.',
    status: 'active' as const,
    created_at: new Date(Date.now() - 18 * 60000).toISOString(),
    resolved_at: null,
    affected_service: 'PostgreSQL Primary',
    assigned_agent: 'MemoryOptimizer-Beta',
    impact: 'High',
    timeline: [
      { time: new Date(Date.now() - 18 * 60000).toISOString(), event: 'Connection pool at 90%' },
      { time: new Date(Date.now() - 15 * 60000).toISOString(), event: 'Pool exhausted — queuing started' },
    ],
  },
  {
    id: 'INC-006',
    severity: 'low' as const,
    title: 'SSL Certificate Expiring Soon',
    description: 'SSL certificate for api.crisisswarm.io expires in 12 days. Auto-renewal scheduled.',
    status: 'resolved' as const,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    resolved_at: new Date(Date.now() - 1.5 * 3600000).toISOString(),
    affected_service: 'API Gateway',
    assigned_agent: 'HealthMonitor-Gamma',
    impact: 'Low',
    timeline: [
      { time: new Date(Date.now() - 2 * 3600000).toISOString(), event: 'Certificate expiry alert triggered' },
      { time: new Date(Date.now() - 1.5 * 3600000).toISOString(), event: 'Auto-renewal configured and confirmed' },
    ],
  },
  {
    id: 'INC-007',
    severity: 'medium' as const,
    title: 'Disk I/O Saturation',
    description: 'Disk I/O wait time spiked to 45ms on storage nodes. Write-back cache optimization applied.',
    status: 'resolved' as const,
    created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    resolved_at: new Date(Date.now() - 2.5 * 3600000).toISOString(),
    affected_service: 'Storage Cluster',
    assigned_agent: 'AutoScaler-Alpha',
    impact: 'Medium',
    timeline: [
      { time: new Date(Date.now() - 3 * 3600000).toISOString(), event: 'I/O wait threshold exceeded' },
      { time: new Date(Date.now() - 2.8 * 3600000).toISOString(), event: 'Cache optimization deployed' },
      { time: new Date(Date.now() - 2.5 * 3600000).toISOString(), event: 'I/O normalized — incident resolved' },
    ],
  },
  {
    id: 'INC-008',
    severity: 'high' as const,
    title: 'Authentication Service Degraded',
    description: 'OAuth token validation latency increased 3x. Affecting user login flows across all regions.',
    status: 'investigating' as const,
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
    resolved_at: null,
    affected_service: 'Auth Service',
    assigned_agent: 'ResponseUnit-Epsilon',
    impact: 'High',
    timeline: [
      { time: new Date(Date.now() - 30 * 60000).toISOString(), event: 'Auth latency spike detected' },
      { time: new Date(Date.now() - 25 * 60000).toISOString(), event: 'ResponseUnit-Epsilon triaging' },
    ],
  },
  {
    id: 'INC-009',
    severity: 'low' as const,
    title: 'Log Aggregation Backlog',
    description: 'Log pipeline experiencing 45-second delay. Non-critical — monitoring data still flowing.',
    status: 'active' as const,
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
    resolved_at: null,
    affected_service: 'Logging Pipeline',
    assigned_agent: 'HealthMonitor-Gamma',
    impact: 'Low',
    timeline: [
      { time: new Date(Date.now() - 45 * 60000).toISOString(), event: 'Pipeline delay detected' },
    ],
  },
  {
    id: 'INC-010',
    severity: 'critical' as const,
    title: 'Primary Database Failover',
    description: 'Primary DB node became unresponsive. Automatic failover to replica completed in 8.2 seconds.',
    status: 'resolved' as const,
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    resolved_at: new Date(Date.now() - 4.8 * 3600000).toISOString(),
    affected_service: 'PostgreSQL Primary',
    assigned_agent: 'ResponseUnit-Epsilon',
    impact: 'Critical',
    timeline: [
      { time: new Date(Date.now() - 5 * 3600000).toISOString(), event: 'Primary DB heartbeat failed' },
      { time: new Date(Date.now() - 4.98 * 3600000).toISOString(), event: 'Failover sequence initiated' },
      { time: new Date(Date.now() - 4.95 * 3600000).toISOString(), event: 'Replica promoted to primary' },
      { time: new Date(Date.now() - 4.8 * 3600000).toISOString(), event: 'Traffic restored — incident resolved' },
    ],
  },
  {
    id: 'INC-011',
    severity: 'medium' as const,
    title: 'CDN Cache Miss Rate Elevated',
    description: 'Cache miss rate at 34% vs baseline of 8%. Causing additional load on origin servers.',
    status: 'resolved' as const,
    created_at: new Date(Date.now() - 6 * 3600000).toISOString(),
    resolved_at: new Date(Date.now() - 5.5 * 3600000).toISOString(),
    affected_service: 'CDN Edge',
    assigned_agent: 'AutoScaler-Alpha',
    impact: 'Medium',
    timeline: [
      { time: new Date(Date.now() - 6 * 3600000).toISOString(), event: 'CDN miss rate alert' },
      { time: new Date(Date.now() - 5.5 * 3600000).toISOString(), event: 'Cache invalidation resolved' },
    ],
  },
  {
    id: 'INC-012',
    severity: 'high' as const,
    title: 'Kubernetes Pod OOMKilled',
    description: '3 pods in the processing namespace killed due to memory limits. Auto-restart successful.',
    status: 'resolved' as const,
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    resolved_at: new Date(Date.now() - 3.7 * 3600000).toISOString(),
    affected_service: 'K8s Processing Namespace',
    assigned_agent: 'MemoryOptimizer-Beta',
    impact: 'High',
    timeline: [
      { time: new Date(Date.now() - 4 * 3600000).toISOString(), event: 'OOMKilled events detected on 3 pods' },
      { time: new Date(Date.now() - 3.9 * 3600000).toISOString(), event: 'Memory limits increased in Helm chart' },
      { time: new Date(Date.now() - 3.7 * 3600000).toISOString(), event: 'Pods running stably — resolved' },
    ],
  },
  {
    id: 'INC-013',
    severity: 'low' as const,
    title: 'Scheduled Job Missed Execution',
    description: 'Nightly data sync job failed to trigger. Manual re-run initiated and completed.',
    status: 'resolved' as const,
    created_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    resolved_at: new Date(Date.now() - 7.5 * 3600000).toISOString(),
    affected_service: 'Batch Processing',
    assigned_agent: 'HealthMonitor-Gamma',
    impact: 'Low',
    timeline: [
      { time: new Date(Date.now() - 8 * 3600000).toISOString(), event: 'Cron job missed at 03:00 UTC' },
      { time: new Date(Date.now() - 7.5 * 3600000).toISOString(), event: 'Manual execution completed' },
    ],
  },
  {
    id: 'INC-014',
    severity: 'medium' as const,
    title: 'API Rate Limit Breaches',
    description: 'External API clients exceeding rate limits at 2.3x normal rate. Throttling applied.',
    status: 'active' as const,
    created_at: new Date(Date.now() - 35 * 60000).toISOString(),
    resolved_at: null,
    affected_service: 'API Gateway',
    assigned_agent: 'NetworkDefense-Delta',
    impact: 'Medium',
    timeline: [
      { time: new Date(Date.now() - 35 * 60000).toISOString(), event: 'Rate limit violation detected' },
      { time: new Date(Date.now() - 30 * 60000).toISOString(), event: 'Throttling rules updated' },
    ],
  },
  {
    id: 'INC-015',
    severity: 'high' as const,
    title: 'Service Mesh mTLS Handshake Failures',
    description: 'Istio sidecar proxy reporting 2.1% handshake failure rate on internal service comms.',
    status: 'investigating' as const,
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    resolved_at: null,
    affected_service: 'Service Mesh',
    assigned_agent: 'NetworkDefense-Delta',
    impact: 'High',
    timeline: [
      { time: new Date(Date.now() - 15 * 60000).toISOString(), event: 'mTLS failure rate exceeded threshold' },
      { time: new Date(Date.now() - 12 * 60000).toISOString(), event: 'NetworkDefense-Delta reviewing certificates' },
    ],
  },
];

// ─── Alerts ──────────────────────────────────────────────────────────────────
export const mockAlerts = [
  {
    id: '1',
    type: 'cpu' as const,
    severity: 'critical' as const,
    message: 'CPU threshold exceeded (85%)',
    created_at: new Date(Date.now() - 2 * 60000).toISOString(),
  },
  {
    id: '2',
    type: 'memory' as const,
    severity: 'high' as const,
    message: 'Memory usage at 88%',
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: '3',
    type: 'response_time' as const,
    severity: 'medium' as const,
    message: 'Response time elevated: 385ms',
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: '4',
    type: 'error_rate' as const,
    severity: 'low' as const,
    message: 'Error rate: 0.5%',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
];

// ─── Swarm Agents ─────────────────────────────────────────────────────────────
export const mockSwarmAgents = [
  {
    id: '1',
    agent_name: 'AutoScaler-Alpha',
    status: 'active' as const,
    current_task: 'Analyzing CPU patterns and planning scale-up',
    created_at: new Date(Date.now() - 60000).toISOString(),
    response_time: 245,
    success_rate: 98,
    cpu_usage: 28,
    memory_usage: 35,
    incidents_handled: 342,
  },
  {
    id: '2',
    agent_name: 'MemoryOptimizer-Beta',
    status: 'investigating' as const,
    current_task: 'Investigating memory leak in cache layer',
    created_at: new Date(Date.now() - 120000).toISOString(),
    response_time: 320,
    success_rate: 95,
    cpu_usage: 42,
    memory_usage: 52,
    incidents_handled: 289,
  },
  {
    id: '3',
    agent_name: 'HealthMonitor-Gamma',
    status: 'idle' as const,
    current_task: 'Ready for incident response',
    created_at: new Date(Date.now() - 30000).toISOString(),
    response_time: 180,
    success_rate: 99,
    cpu_usage: 15,
    memory_usage: 22,
    incidents_handled: 456,
  },
  {
    id: '4',
    agent_name: 'NetworkDefense-Delta',
    status: 'active' as const,
    current_task: 'Monitoring DDoS attack patterns and mitigation',
    created_at: new Date(Date.now() - 90000).toISOString(),
    response_time: 195,
    success_rate: 97,
    cpu_usage: 38,
    memory_usage: 48,
    incidents_handled: 521,
  },
  {
    id: '5',
    agent_name: 'ResponseUnit-Epsilon',
    status: 'active' as const,
    current_task: 'Executing automated remediation procedures',
    created_at: new Date(Date.now() - 45000).toISOString(),
    response_time: 210,
    success_rate: 96,
    cpu_usage: 32,
    memory_usage: 41,
    incidents_handled: 378,
  },
  {
    id: '6',
    agent_name: 'TelemetryStreamer-Zeta',
    status: 'idle' as const,
    current_task: 'Streaming system health metrics to dashboard',
    created_at: new Date(Date.now() - 15000).toISOString(),
    response_time: 120,
    success_rate: 99,
    cpu_usage: 12,
    memory_usage: 18,
    incidents_handled: 512,
  },
];

// ─── Dashboard KPIs ───────────────────────────────────────────────────────────
export const mockMetrics = {
  total_incidents: 12,
  active_alerts: 4,
  system_health: 72,
  response_time_avg: 245,
  cpu_avg: 58,
  memory_avg: 65,
  request_rate: 2480,
};

// ─── Terminal Logs ────────────────────────────────────────────────────────────
export const mockTerminalLogs = [
  {
    id: '1',
    timestamp: new Date(Date.now() - 0).toLocaleTimeString(),
    agent: 'AutoScaler-Alpha',
    status: 'success' as const,
    message: 'Load balancing optimization complete',
  },
  {
    id: '2',
    timestamp: new Date(Date.now() - 5000).toLocaleTimeString(),
    agent: 'NetworkDefense-Delta',
    status: 'warning' as const,
    message: 'Elevated network traffic detected',
  },
  {
    id: '3',
    timestamp: new Date(Date.now() - 10000).toLocaleTimeString(),
    agent: 'MemoryOptimizer-Beta',
    status: 'info' as const,
    message: 'Cache layer optimization in progress',
  },
  {
    id: '4',
    timestamp: new Date(Date.now() - 15000).toLocaleTimeString(),
    agent: 'ResponseUnit-Epsilon',
    status: 'success' as const,
    message: 'Incident mitigation deployed successfully',
  },
  {
    id: '5',
    timestamp: new Date(Date.now() - 20000).toLocaleTimeString(),
    agent: 'HealthMonitor-Gamma',
    status: 'success' as const,
    message: 'System health check: 94% operational',
  },
];

// ─── Service Breakdown (for Analytics) ───────────────────────────────────────
export const mockServiceData = [
  { service: 'API Gateway',      requests: 48200, errors: 192, latency: 245, health: 96 },
  { service: 'Auth Service',     requests: 22400, errors: 448, latency: 380, health: 78 },
  { service: 'Database',         requests: 35600, errors: 71,  latency: 42,  health: 99 },
  { service: 'Storage Cluster',  requests: 18900, errors: 38,  latency: 65,  health: 98 },
  { service: 'CDN Edge',         requests: 92100, errors: 184, latency: 18,  health: 94 },
  { service: 'Service Mesh',     requests: 31400, errors: 660, latency: 128, health: 72 },
  { service: 'Batch Processing', requests: 4200,  errors: 84,  latency: 890, health: 85 },
];

// ─── Error Rate Trend (for Analytics) ────────────────────────────────────────
export const mockErrorRateTrend = [
  { time: '00:00', errorRate: 0.1, requests: 1200 },
  { time: '02:00', errorRate: 0.2, requests: 800  },
  { time: '04:00', errorRate: 0.1, requests: 600  },
  { time: '06:00', errorRate: 0.5, requests: 2100 },
  { time: '08:00', errorRate: 0.8, requests: 4800 },
  { time: '09:00', errorRate: 1.2, requests: 5600 },
  { time: '10:00', errorRate: 0.4, requests: 4200 },
  { time: '12:00', errorRate: 0.3, requests: 3900 },
  { time: '14:00', errorRate: 0.9, requests: 5100 },
  { time: '16:00', errorRate: 0.4, requests: 4300 },
  { time: '18:00', errorRate: 0.2, requests: 3100 },
  { time: '20:00', errorRate: 0.1, requests: 2200 },
  { time: '22:00', errorRate: 0.1, requests: 1500 },
];

// ─── Agent Performance Heatmap ────────────────────────────────────────────────
export const mockAgentHeatmap = [
  { agent: 'AutoScaler-Alpha',     h00:99, h02:98, h04:97, h06:95, h08:92, h10:97, h12:98, h14:90, h16:96, h18:99, h20:100, h22:99 },
  { agent: 'MemoryOptimizer-Beta', h00:95, h02:96, h04:94, h06:88, h08:82, h10:90, h12:93, h14:85, h16:91, h18:95, h20:97,  h22:96 },
  { agent: 'HealthMonitor-Gamma',  h00:100,h02:100,h04:99, h06:98, h08:96, h10:99, h12:100,h14:97, h16:99, h18:100,h20:100, h22:100},
  { agent: 'NetworkDefense-Delta', h00:97, h02:96, h04:97, h06:91, h08:85, h10:93, h12:96, h14:88, h16:94, h18:97, h20:98,  h22:97 },
  { agent: 'ResponseUnit-Epsilon', h00:96, h02:95, h04:96, h06:93, h08:87, h10:95, h12:95, h14:89, h16:93, h18:96, h20:97,  h22:96 },
];
